In [ ]:
# Converts original demo_matrix to have cluster labels instead of region labels

In [1]:
import numpy as np

In [2]:
demo_matrix_orig = np.load('../../data/extracts/demo_matrix.npy')

In [3]:
demo_matrix_orig

array([[ 2.,  2.],
       [ 2.,  2.],
       [ 3.,  2.],
       ..., 
       [ 5.,  2.],
       [ 3.,  2.],
       [ 2.,  1.]])

In [5]:
cluster_array = np.load('../../data/extracts/cluster1CustmeridsMapping.npy')

In [6]:
cluster_array

array([[ 5.],
       [ 6.],
       [ 7.],
       ..., 
       [ 7.],
       [ 2.],
       [ 5.]])

In [9]:
demo_matrix_orig[:,0] = cluster_array[:,0]

In [10]:
demo_matrix_orig

array([[ 5.,  2.],
       [ 6.,  2.],
       [ 7.,  2.],
       ..., 
       [ 7.,  2.],
       [ 2.,  2.],
       [ 5.,  1.]])

In [12]:
np.save('../../data/extracts/demo_matrix_c1.npy',demo_matrix_orig)